import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import FingerprintJS, { SourcesToComponents, UnknownComponents } from '@fingerprintjs/fingerprintjs'
import { useEffect, useState } from 'react'

export default function Fingerprint() {

    const [originalFp, setOriginalFp] = useState('');
    const [deviceOSFp, setDeviceOSFp] = useState('');
    const [browserFp, setBrowserFp] = useState('')

    const originalFingerprint = async () => {
        const fpPromise = FingerprintJS.load()
        const fp = await fpPromise;
        const result = await fp.get()

        // This is the visitor identifier:
        const visitorId = result.visitorId
        setOriginalFp(visitorId);
        // return visitorId;
    }

    const deviceOSFingerprint = async () => {
        const fpPromise = FingerprintJS.load()
        const fp = await fpPromise;
        const result = await fp.get()
        const {
            hardwareConcurrency,
            colorDepth,
            platform,
            timezone,
            touchSupport,
            cpuClass,
            hdr,
            invertedColors,
            monochrome,
            reducedMotion
        } = result.components

        let customComponent = {
            hardwareConcurrency,
            colorDepth,
            platform,
            timezone,
            touchSupport,
            cpuClass,
            hdr,
            invertedColors,
            monochrome,
            reducedMotion
        }

        // This is the visitor identifier:
        console.log(customComponent);
        const visitorId = FingerprintJS.hashComponents(customComponent)
        setDeviceOSFp(visitorId);
    }

    const deviceOSBrowserFingerprint = async () => {
        const fpPromise = FingerprintJS.load()
        const fp = await fpPromise;
        const result = await fp.get()

        const { plugins, screenFrame, screenResolution, ...components } = result.components;

        let customComponent = { ...components }

        if (customComponent.canvas.value) {
            customComponent = {
                ...customComponent,
                canvas: {
                    ...customComponent.canvas,
                    value: {
                        ...customComponent.canvas.value,
                        text: '',
                    },
                },
            }
        }
        console.log(customComponent);
        const visitorId = FingerprintJS.hashComponents(customComponent)
        setBrowserFp(visitorId);
    }

    useEffect(() => {
        originalFingerprint();
        deviceOSFingerprint();
        deviceOSBrowserFingerprint();
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h3>Original: {originalFp}</h3>
                <h3 style={{ color: 'blue' }}>Device: {deviceOSFp}</h3>
                <h3>Browser: {browserFp}</h3>
            </main>

            <footer className={styles.footer}>
                <a
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
